#pragma once
#ifndef __COMPILER_AST_H__
#define __COMPILER_AST_H__

#include "types.h"
#include "tree.h"
#include "node.h"

tree_node* ast_node_compilation_unit();
tree_node* ast_node_name_unit();
tree_node* ast_node_name();
tree_node* ast_node_class_type_unit();
tree_node* ast_node_class_type();
tree_node* ast_node_interface_type_unit();
tree_node* ast_node_interface_type();
tree_node* ast_node_interface_type_list();
tree_node* ast_node_package_declaration();
tree_node* ast_node_import_declaration();
tree_node* ast_node_top_level();
tree_node* ast_node_class_declaration();
tree_node* ast_node_interface_declaration();
tree_node* ast_node_class_extends();
tree_node* ast_node_class_implements();
tree_node* ast_node_class_body();
tree_node* ast_node_interface_extends();
tree_node* ast_node_interface_body();
tree_node* ast_node_interface_body_declaration();
tree_node* ast_node_class_body_declaration();
tree_node* ast_node_static_initializer();
tree_node* ast_node_block();
tree_node* ast_node_constructor_declaration();
tree_node* ast_node_type();
tree_node* ast_node_method_header();
tree_node* ast_node_method_declaration();
tree_node* ast_node_variable_declarators();
tree_node* ast_node_formal_parameter_list();
tree_node* ast_node_formal_parameter();
tree_node* ast_node_throws();
tree_node* ast_node_argument_list();
tree_node* ast_node_constructor_body();
tree_node* ast_node_method_body();
tree_node* ast_node_variable_declarator();
tree_node* ast_node_array_initializer();
tree_node* ast_node_primary();
tree_node* ast_node_primary_simple();
tree_node* ast_node_primary_complex();
tree_node* ast_node_primary_creation();
tree_node* ast_node_primary_array_creation();
tree_node* ast_node_primary_class_instance_creation();
tree_node* ast_node_primary_method_invocation();
tree_node* ast_node_primary_array_access();
tree_node* ast_node_primary_class_literal();
tree_node* ast_node_expression();
tree_node* ast_node_operator();
tree_node* ast_node_statement(bool need_data);
tree_node* ast_node_constructor_invocation();
tree_node* ast_node_switch_label();
tree_node* ast_node_for_init();
tree_node* ast_node_for_update();
tree_node* ast_node_ambiguous();
tree_node* ast_node_expression_list();

#endif
