#include "langspec.h"

java_reserved_word java_reserved_words[] =
{
    { "public", JLT_RWD_PUBLIC, 0, 0 },
    { "private", JLT_RWD_PRIVATE, 0, 0 },
    { "protected", JLT_RWD_PROTECTED, 0, 0 },
    { "final", JLT_RWD_FINAL, 0, 0 },
    { "static", JLT_RWD_STATIC, 0, 0 },
    { "abstract", JLT_RWD_ABSTRACT, 0, 0 },
    { "transient", JLT_RWD_TRANSIENT, 0, 0 },
    { "synchronized", JLT_RWD_SYNCHRONIZED, 0, 0 },
    { "volatile", JLT_RWD_VOLATILE, 0, 0 },

    { "default", JLT_RWD_DEFAULT, 0, 0 },
    { "if", JLT_RWD_IF, 0, 0 },
    { "throw", JLT_RWD_THROW, 0, 0 },
    { "boolean", JLT_RWD_BOOLEAN, 0, 0 },
    { "do", JLT_RWD_DO, 0, 0 },
    { "implements", JLT_RWD_IMPLEMENTS, 0, 0 },
    { "throws", JLT_RWD_THROWS, 0, 0 },
    { "break", JLT_RWD_BREAK, 0, 0 },
    { "double", JLT_RWD_DOUBLE, 0, 0 },
    { "import", JLT_RWD_IMPORT, 0, 0 },
    { "byte", JLT_RWD_BYTE, 0, 0 },
    { "else", JLT_RWD_ELSE, 0, 0 },
    { "instanceof", JLT_RWD_INSTANCEOF, 0, 0 },
    { "return", JLT_RWD_RETURN, 0, 0 },
    { "try", JLT_RWD_TRY, 0, 0 },
    { "case", JLT_RWD_CASE, 0, 0 },
    { "extends", JLT_RWD_EXTENDS, 0, 0 },
    { "int", JLT_RWD_INT, 0, 0 },
    { "short", JLT_RWD_SHORT, 0, 0 },
    { "void", JLT_RWD_VOID, 0, 0 },
    { "catch", JLT_RWD_CATCH, 0, 0 },
    { "interface", JLT_RWD_INTERFACE, 0, 0 },
    { "char", JLT_RWD_CHAR, 0, 0 },
    { "finally", JLT_RWD_FINALLY, 0, 0 },
    { "long", JLT_RWD_LONG, 0, 0 },
    { "super", JLT_RWD_SUPER, 0, 0 },
    { "while", JLT_RWD_WHILE, 0, 0 },
    { "class", JLT_RWD_CLASS, 0, 0 },
    { "float", JLT_RWD_FLOAT, 0, 0 },
    { "native", JLT_RWD_NATIVE, 0, 0 },
    { "switch", JLT_RWD_SWITCH, 0, 0 },
    { "for", JLT_RWD_FOR, 0, 0 },
    { "new", JLT_RWD_NEW, 0, 0 },
    { "continue", JLT_RWD_CONTINUE, 0, 0 },
    { "package", JLT_RWD_PACKAGE, 0, 0 },
    { "this", JLT_RWD_THIS, 0, 0 },

    { "const", JLT_RWD_CONST, 0, DP_C_FAMILY },
    { "goto", JLT_RWD_GOTO, 0, DP_C_FAMILY },

    { "true", JLT_RWD_TRUE, 0, 0 },
    { "false", JLT_RWD_FALSE, 0, 0 },
    { "null", JLT_RWD_NULL, 0, 0 },
};

const unsigned int num_java_reserved_words = ARRAY_SIZE(java_reserved_words);
