#include "langspec.h"

java_reserved_word java_reserved_words[] =
{
    { "public", RWID_PUBLIC, 0, 0 },
    { "private", RWID_PRIVATE, 0, 0 },
    { "protected", RWID_PROTECTED, 0, 0 },
    { "final", RWID_FINAL, 0, 0 },
    { "static", RWID_STATIC, 0, 0 },
    { "abstract", RWID_ABSTRACT, 0, 0 },
    { "transient", RWID_TRANSIENT, 0, 0 },
    { "synchronized", RWID_SYNCHRONIZED, 0, 0 },
    { "volatile", RWID_VOLATILE, 0, 0 },

    { "default", RWID_DEFAULT, 0, 0 },
    { "if", RWID_IF, 0, 0 },
    { "throw", RWID_THROW, 0, 0 },
    { "boolean", RWID_BOOLEAN, 0, 0 },
    { "do", RWID_DO, 0, 0 },
    { "implements", RWID_IMPLEMENTS, 0, 0 },
    { "throws", RWID_THROWS, 0, 0 },
    { "break", RWID_BREAK, 0, 0 },
    { "double", RWID_DOUBLE, 0, 0 },
    { "import", RWID_IMPORT, 0, 0 },
    { "byte", RWID_BYTE, 0, 0 },
    { "else", RWID_ELSE, 0, 0 },
    { "instanceof", RWID_INSTANCEOF, 0, 0 },
    { "return", RWID_RETURN, 0, 0 },
    { "try", RWID_TRY, 0, 0 },
    { "case", RWID_CASE, 0, 0 },
    { "extends", RWID_EXTENDS, 0, 0 },
    { "int", RWID_INT, 0, 0 },
    { "short", RWID_SHORT, 0, 0 },
    { "void", RWID_VOID, 0, 0 },
    { "catch", RWID_CATCH, 0, 0 },
    { "interface", RWID_INTERFACE, 0, 0 },
    { "char", RWID_CHAR, 0, 0 },
    { "finally", RWID_FINALLY, 0, 0 },
    { "long", RWID_LONG, 0, 0 },
    { "super", RWID_SUPER, 0, 0 },
    { "while", RWID_WHILE, 0, 0 },
    { "class", RWID_CLASS, 0, 0 },
    { "float", RWID_FLOAT, 0, 0 },
    { "native", RWID_NATIVE, 0, 0 },
    { "switch", RWID_SWITCH, 0, 0 },
    { "for", RWID_FOR, 0, 0 },
    { "new", RWID_NEW, 0, 0 },
    { "continue", RWID_CONTINUE, 0, 0 },
    { "package", RWID_PACKAGE, 0, 0 },
    { "this", RWID_THIS, 0, 0 },

    { "const", RWID_CONST, 0, DP_C_FAMILY },
    { "goto", RWID_GOTO, 0, DP_C_FAMILY },

    { "true", RWID_TRUE, 0, 0 },
    { "false", RWID_FALSE, 0, 0 },
    { "null", RWID_NULL, 0, 0 },
};

const unsigned int num_java_reserved_words = ARRAY_SIZE(java_reserved_words);
